@startuml
!include style.iuml
scale 1.3

namespace Qt {
    ' class QTimer {
    '     +{static} void singleShot(Duration)
    '     +{static} void timeout()
    ' }

    class QObject
    ' class QVariant

    QModbusServer <|-- QModbusTcpServer
    QModbusDevice <|-- QModbusServer
    QObject <|-- QModbusDevice
}

namespace modbusio {
    enum TransmitedType {
        Bool
        Word
        DoubleWord
        Real
        LongReal
    }

    enum Relation {
        Eq
        Ne
        Gt
        Lt
        Ge
        Le
    }

    interface IDeviceWriter {
        + {abstract} void write(const ModbusData&) = 0
    }

    IDeviceWriter <|--- ModbusDeviceImpl
    Qt.QModbusTcpServer <|-- ModbusDeviceImpl

    class ModbusIoManager {
        + setCaptures(IModbusElementWriter[])

        + [signal] void writed(const ModbusData&)
        + [slot] void newModbusData(const ModbusData&)
        + [slot] void resetAll()
        + [slot] void startAll()

        - addCapture(IModbusElementWriter)
        - captures[]: IModbusElementWriter
    }

    class ModbusElement {
        + string title()
        + uint8_t address()
        + TransmitedType type()
        + string position()
        + string description()
    }

    class ModbusData {
        - value : Value
        ' + void setValue(Data)
        + Value value()
    }

    class ModbusDataRelationed {
        - relation: Relation
    }

    interface IModbusElementWriter {
        + {abstract} [signal] virtual void writed(const ModbusData&) = 0
        + {abstract} [signal] virtual void modbusDataChanged(const ModbusData&) = 0

        + {abstract} [slot] virtual void start() = 0
        + {abstract} [slot] virtual void reset() = 0
        + {abstract} [slot] virtual void newModbusData(const ModbusData&) = 0

        + {abstract} virtual void write() = 0        
        + {abstract} virtual bool conditionsMet(const ModbusData&) = 0
    }

    interface ModbusElementReader {
        + ModbusData read() const
    }

    class ModbusPeriodicWriter {
        - QVariant value
        - millisecond period
    }

    class ModbusGuardedWriter {
        - [override] bool conditionsMet(const ModbusData&)
        # condition : ModbusDataRelationed
        # device : IDeviceWriter
    }

    class ModbusDelayedWriter {
        - [override] [slot] virtual void newModbusData(const ModbusData&)
        - delay : Time
    }

    class ModbusMultiguardedWriter {
        - [override] bool conditionsMet(const ModbusData&)
        # conditions[]: ModbusDataRelationed
        # device : IDeviceWriter
    }

    class ModbusDelayedMultiguardWriter {
        - [override] [slot] virtual void newModbusData(const ModbusData&)
        - delay : Time
    }

    ModbusElement *-- TransmitedType
    ModbusElement <|-right- ModbusData
    ' ModbusData *-- Qt.QVariant

    ModbusData <|-right- ModbusDataRelationed
    ModbusDataRelationed *-right- Relation

    ModbusData <|-- IModbusElementWriter 
    Qt.QObject <|-down- IModbusElementWriter
    ModbusData <|-right- ModbusElementReader 

    ModbusMultiguardedWriter <|-- ModbusPeriodicWriter

    IModbusElementWriter <|-- ModbusGuardedWriter
    ModbusGuardedWriter "1" *-- "1" IDeviceWriter
    
    ModbusGuardedWriter <|--- ModbusDelayedWriter
    
    IModbusElementWriter <|-- ModbusMultiguardedWriter
    ModbusMultiguardedWriter "1" *-- "1" IDeviceWriter

    ModbusMultiguardedWriter <|--- ModbusDelayedMultiguardWriter

    ModbusIoManager *-left- IModbusElementWriter
}

@enduml