@startuml
!include style.iuml

namespace Qt {
    class QObject
    class QVariant
}

namespace modbusio {
    enum TransmitedType {
        Bool,
        Word,
        DoubleWord,
        Real,
        LongReal
    }

    interface IDeviceWriter {
        + {abstract} void write(const ModbusData&) = 0
    }

    class ModbusElement {
        + string title()
        + uint8_t address()
        + TransmitedType type()
        + string position()
        + string description()
    }

    class ModbusData {
        - value : QVariant
        ' + void setValue(Data)
        + QVariant value()
    }

    interface IModbusElementWriter {
        + {abstract} [signal] virtual void writed(const ModbusData&) = 0
        + {abstract} [signal] virtual void modbusDataChanged(const ModbusData&) = 0

        + {abstract} [slot] virtual void start() = 0
        + {abstract} [slot] virtual void reset() = 0
        + {abstract} [slot] virtual void newModbusData(const ModbusData&) = 0

        + {abstract} virtual void write() = 0        
        + {abstract} virtual bool conditionsMet(const ModbusData&) = 0
    }

    interface IModbusElementReader {
        + ModbusData read() const
    }

    class ModbusPeriodicWriter {
        - QVariant value
        - millisecond period
    }

    class ModbusGuardedWriter {
        - [override] bool conditionsMet(const ModbusData&)
        # condition : ModbusData
        # device : IDeviceWriter
    }

    class ModbusDelayedWriter {
        - [override] [slot] virtual void newModbusData(const ModbusData&)
        - delay : Time
    }

    class ModbusMultiguardedWriter {
        - [override] bool conditionsMet(const ModbusData&)
        # conditions[]: ModbusData
        # device : IDeviceWriter
    }

    class ModbusDelayedMultiguardWriter {
        - [override] [slot] virtual void newModbusData(const ModbusData&)
        - delay : Time
    }

    ModbusElement *-- TransmitedType
    ModbusElement <|-right- ModbusData
    ModbusData *-- Qt.QVariant

    ModbusData <|-- IModbusElementWriter 
    Qt.QObject <|-down- IModbusElementWriter
    ModbusData <|-right- IModbusElementReader

    ModbusElementImpl <|-- ModbusPeriodicWriter
    ModbusPeriodicWriter "1" *-- "1" IDeviceWriter
    ModbusPeriodicWriter "1" *-- "1" Qt.QVariant
    ModbusPeriodicWriter "1" *-- "1" Qt.QTimer

    IModbusElementWriter <|-- ModbusElementImpl

    ModbusElementImpl <|-- ModbusGuardedWriter
    ModbusGuardedWriter "1" *-- "1" IDeviceWriter
    
    ModbusGuardedWriter <|--- ModbusDelayedWriter
    ModbusDelayedWriter "1" *-- "1" Qt.QTimer
    
    ModbusElementImpl <|-- ModbusMultiguardedWriter 
    ModbusMultiguardedWriter "1" *-- "1" IDeviceWriter

    ModbusMultiguardedWriter <|--- ModbusDelayedMultiguardWriter
    ModbusDelayedMultiguardWriter "1" *-- "1" Qt.QTimer
}

@enduml