@startuml

robust "ModbusMultiguardedWriter" as guard
concise "Condition 1" as cond1
concise "Condition 2" as cond2
concise "Condition n" as condn

@0
cond1 is false
cond2 is false
condn is false
guard is Ожидает

@50
cond2 is true
guard is Ожидает

@100
cond2 is false
condn is true
guard is Ожидает


@150
cond1 -> guard : Последнее условие выполнено
cond1 is true
cond2 is true
condn is true
guard is Записано



@250
cond1 is false
cond2 is true
condn is true
guard is Записано

@300
cond2 is false
condn is true
guard is Записано

@400
condn -> guard : Записано
condn is false
guard is Записано


@enduml