@startuml
!include style.iuml

package modbus::io {
    [ModbusIoManager] as manager
    () IModbusElementWriter as iwriter #D0DDDD
    manager -- iwriter
    iwriter ----> IDeviceWriter
    [ModbusPeriodicWriter] -up- iwriter
    [ModbusGuardedWriter] -up- iwriter
    [ModbusDelayedWriter] -up- [ModbusGuardedWriter]
    [ModbusMultiguardedWriter] -up- iwriter
    [ModbusDelayedMultiguardedWriter] -up- [ModbusMultiguardedWriter]
}

database Scenarios #D0DDD0 {
    folder NormalScenarios
    folder CriticalScenarios
}

database ModbusTags #D0DDDD {
    folder Object1
    folder Object2    
}

package parser {
    () IParser
    [ScenarioParser] -[dashed]up- [TagChecker]
    [TagsParser]
}

manager -up-> IParser
IParser -right- [ScenarioParser]
[ScenarioParser] -right- Scenarios

TagsParser -right- IParser
TagsParser -- ModbusTags
TagChecker -[dashed]- ModbusTags


@enduml