@startuml
!include style.iuml

robust "ModbusDelayedWriter" as guard
concise "Condition" as cond

@cond
0 is false #Gray
100 is true #Green
200 is false #Gray

cond@100 -> guard@100 : Выполнение условия
guard@+100 -> cond@+100 : Задержка еще не истекла

@guard
0 is Ожидает
@100 <-> @+300 : delay = 300 
400 is Записано

@+50

@enduml