@startuml
!include style.iuml

namespace Qt {
    QModbusServer <|-- QModbusTcpServer
    QModbusDevice <|-- QModbusServer
    QObject <|-- QModbusDevice
}

namespace modbus::io {
    interface IDeviceWriter {
        + {abstract} void write(const ModbusData&) = 0
        + [signal] void writed(const ModbusData&)
    }

    class ModbusDeviceImpl {
        + [override] void write(const ModbusData&)
    }

    IDeviceWriter <|-- ModbusDeviceImpl
    Qt.QModbusTcpServer <|-- ModbusDeviceImpl
}

@enduml