@startuml
!include style.iuml

robust "ModbusGuardedWriter" as guard
concise "Condition" as cond

@0
cond is false
guard is Ожидает

@+100
cond is true
guard is Записано

@+100
cond -> guard : Сохранено
cond is false
guard is Записано

@+50

@enduml