@startuml
!include style.iuml
hide empty description

[*] --> Инициализация : ** manager = ModbusIoManager::instance()**
    Инициализация: Чтение конфигурационного файла.

АНПА --> Сценарий

Сценарий -> Инициализация
    Сценарий: Штатный;
    Сценарий: Критический.

Инициализация --> Готов : ** manager.setCaptures()**
    Готов: Ожидание запуска.

Готов --> Ожидание : ** manager.startAll()**
    Ожидание: Ожидание данных **ModbusData**;
    Ожидание: Делегирование данных.

Modbus -> Ожидание

Ожидание --> Обработка 
    Обработка: Изменение состояния.

Обработка --> Ожидание 

Обработка --> [*] : ** manager.stop()**

@endwhile