@startuml
!include style.iuml

robust "ModbusGuardedWriter" as guard
concise "Condition" as cond

@cond
0 is false #Gray
100 is true #Green
200 is false #Gray

@guard
0 is Ожидает
100  is Записано

guard@+100 -> cond@+100 : Сохранено

@+50

@enduml