@startuml
!include style.iuml

robust "ModbusDelayedMultiguardWriter" as guard
concise "Condition 1" as cond1
concise "Condition 2" as cond2

@cond1
0 is false #Gray
50 is true #Green
150 is false #Gray

@cond2
0 is false #Gray
100 is true #Green
150 is false #Gray

@guard
0 is Ожидает
@100 <-> @+200 : delay = 200 
300 is Записано

cond2@100 -> guard@100 : Последнее условие выполнено

@+50

@enduml