@startuml
!include style.iuml

robust "ModbusGuardedWriter" as guard
concise "Condition" as cond

@cond
0 is false #LightGray
100 is true #LightGreen
200 is false #LightGray

@guard
0 is Ожидает
100  is Записано

guard@+100 -> cond@+100 : Сохранено

@+50

@enduml