@startuml
!include style.iuml

robust "ModbusMultiguardedWriter" as guard
concise "Condition 1" as cond1
concise "Condition 2" as cond2
concise "Condition n" as condn

cond1@150 -> guard@150 : Последнее условие выполнено
condn@400 -> guard@400 : Записано

@cond1
0 is false #Gray
150 is true #Green
250 is false #Gray

@cond2
0 is false #Gray
50 is true #Green
100 is false #Gray
150 is true #Green
300 is false #Gray 

@condn
0 is false #Gray
100 is true #Green
400 is false #Gray

@guard
0 is Ожидает
150 is Записано

@+50

@enduml