@startuml
!include style.iuml

' title **Декомпозиция материальной составляющей АНПА на составные части**

usecase pu as "**Прибор управления**
..
Анализатор приемо-излучательного тракта\nсистема поиска и обнаружения
..
Установщик режима двигателя
..
Установщик курса
..
Установщик глубины
"

usecase spo as "**Система поиска и обнаружения**
..
Излучатель
..
Приемник
"

usecase sud as "**Система управления двигателем**
..
Блок управления двигателем
..
Двигатель
..
Редуктор
"

usecase rp as "**Рулевой привод**
..
Рулевые машинки
..
Рули
"

usecase d as "**Движитель**
..
Лопасти
"

usecase akb as "**Аккумуляторная батарея**
..
Блок управления\nбатареей
..
Элементы\nпитания
"

pu -left-> spo
pu -right-> rp
pu -down-> sud

sud -left-> d
sud -right-> akb

@enduml