@startuml
!include style.iuml
scale 1.5

actor Оператор as user

box "Программное обеспечение" #LightBlue
    participant "Программное обеспечение\nимитатора" as imit #D0D0D0
    participant "Программное обеспечение\nверхневого уровня" as main #F0D0D0
end box

box "Конфигурация" #D0D0D0
    database "Modbus\nпараметры" as tags #LightBlue
    database Сценарии as scen #LightGreen
end box

autonumber
== Инициализация ==
user -> scen: Выбор сценария
user -> main: Выбор изделия
main <- tags: Загрузка конфигурации
== Загрузка конфигурации ==
scen -> tags: Проверка
scen -> scen: Валидные данные
note over tags, scen #FAFAFA: Каждый элемент\nсценария принадлежит\nModbus
scen -> imit: Загрузка данных сценария
user -> imit: Запуск
user -> main: Выбор проверки согласно сценарию
||50||
== Выполнение сценария проверки ==
...
imit <-[#0000F0]> main : Обмен сообщениями\nпо протоколу Modbus
autonumber stop

== Окончание проверки ==
user -> main: <font color=red>stop</font>
user -> imit: <font color=red>stop</font>

@enduml